blank_issues_enabled: false
contact_links:
  - name: Discode Community
    url: https://discord.gg/X63NSFab
    about: Join our Discode for fast help and gist
  - name: Kaduna Bitdevs
    url: https://twitter.com/bitdevskaduna
    about: Our home community