blank_issues_enabled: false
contact_links:
  - name: Telegram Community
    url: https://t.me/sabiwallet
    about: Join our Telegram for fast help and gist
  - name: Kaduna Bitdevs
    url: https://twitter.com/bitdevskaduna
    about: Our home community